title: Learning About GitHub Pages
author: GitHub Pages Beginner User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Example of description for a GitHub Pages site.  It can be edited in _config.yml. 
  It will appear in the document head meta (for Google search results) 
  and in the feed.xml site description.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
